apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: opensearch.modules.elastisys.com
spec:
  compositeTypeRef:
    apiVersion: modules.elastisys.com/v1alpha1
    kind: OpenSearch
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: opensearch-master
            base:
              apiVersion: helm.crossplane.io/v1beta1
              kind: Release
              metadata:
                name: opensearch-master
              spec:
                providerConfigRef:
                  name: helm
                forProvider:
                  wait: true
                  namespace: opensearch-system
                  chart:
                    repository: https://opensearch-project.github.io/helm-charts
                    name: opensearch
                    version: "2.26.1"
                  values:
                    networkPolicy:
                      create: true
                    rbac:
                      create: true
                    persistence:
                      enableInitChown: false
                    secretMounts:
                      - secretName: opensearch-transport-cert
                        name: opensearch-transport-cert
                        path: /usr/share/opensearch/config/transport
                        defaultMode: 0400
                      - secretName: opensearch-http-cert
                        name: opensearch-http-cert
                        path: /usr/share/opensearch/config/http
                        defaultMode: 0400
                    securityContext:
                      runAsNonRoot: true
                      runAsGroup: 1000
                      runAsUser: 1000
                      capabilities:
                        drop:
                          - ALL
                    podSecurityContext:
                      fsGroup: 1000
                    # To prevent the demo certs from generating: https://github.com/opensearch-project/helm-charts/issues/154
                    extraEnvs:
                      - name: DISABLE_INSTALL_DEMO_CONFIG
                        value: "true"
                    # This is a workaround to set vm.max_map_count before OpenSearch starts.
                    # The chart provides this using non privileged container, and instead allows the unsafe sysctl through PSP.
                    # However this relies on the unsafe sysctl to be allowed in kubelet, which it is not by default.
                    extraInitContainers:
                      - name: init-sysctl
                        image: ghcr.io/elastisys/curl-jq:1.0.0
                        command:
                          - sysctl
                          - -w
                          - vm.max_map_count=262144
                        securityContext:
                          allowPrivilegeEscalation: true
                          privileged: true
                          runAsNonRoot: false
                          runAsUser: 0
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.roles
                toFieldPath: spec.forProvider.values.roles
              - type: FromCompositeFieldPath
                fromFieldPath: spec.clusterName
                toFieldPath: spec.forProvider.values.clusterName
              - type: FromCompositeFieldPath
                fromFieldPath: spec.clusterName
                toFieldPath: spec.forProvider.values.masterService
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-master"
              - type: FromCompositeFieldPath
                fromFieldPath: spec.replicas
                toFieldPath: spec.forProvider.values.replicas
              - type: FromCompositeFieldPath
                fromFieldPath: spec.opensearchJavaOpts
                toFieldPath: spec.forProvider.values.opensearchJavaOpts
              - type: FromCompositeFieldPath
                fromFieldPath: spec.plugins
                toFieldPath: spec.forProvider.values.plugins
              - type: FromCompositeFieldPath
                fromFieldPath: spec.keystore
                toFieldPath: spec.forProvider.values.keystore
              - type: FromCompositeFieldPath
                fromFieldPath: spec.config
                toFieldPath: spec.forProvider.values.config
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resources
                toFieldPath: spec.forProvider.values.resources
