apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: logwrites.capabilities.elastisys.com
spec:
  compositeTypeRef:
    apiVersion: capabilities.elastisys.com/v1alpha1
    kind: LogWrite
  mode: Pipeline
  pipeline:
    - step: discovery
      functionRef:
        name: function-extra-resources
      input:
        apiVersion: extra-resources.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          extraResources:
            - apiVersion: modules.elastisys.com/v1alpha1
              kind: OpenSearch
              into: producers
              type: Selector
              selector:
                maxMatch: 1
                minMatch: 0
                matchLabels:
                  - key: logwrites.capabilities.elastisys.com
                    type: Value
                    value: ""
            - apiVersion: v1
              kind: Secret
              into: consumers
              type: Selector
              selector:
                maxMatch: 2
                minMatch: 0
                matchLabels:
                  - key: logwrites.capabilities.elastisys.com
                    type: Value
                    value: ""
    - step: consumers-environment-config
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $localConsumers := index (index .context "apiextensions.crossplane.io/extra-resources") "consumers" }}
            apiVersion: apiextensions.crossplane.io/v1beta1
            kind: EnvironmentConfig
            metadata:
              name: consumers.logwrites.capabilities.elastisys.com
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: environment-config-consumers
                gotemplating.fn.crossplane.io/ready: "True"
            data:
              secretRefs:
                {{- range $_, $r := $localConsumers }}
                - name: {{ $r.metadata.name }}
                  namespace: {{ $r.metadata.namespace }}
                {{- end }}
    - step: remote-consumer-discovery
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- range $_, $cluster := .observed.composite.resource.spec.clusters }}
            ---
            apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            metadata:
              name: remote-consumers-environment-config-{{ $cluster }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: remote-consumers-environment-config-{{ $cluster }}
                gotemplating.fn.crossplane.io/ready: "True"
            spec:
              providerConfigRef:
                name: kubernetes-{{ $cluster }}
              managementPolicies: [Observe]
              watch: true
              forProvider:
                manifest:
                  apiVersion: apiextensions.crossplane.io/v1beta1
                  kind: EnvironmentConfig
                  metadata:
                    name: consumers.logwrites.capabilities.elastisys.com
            {{- end }}
    - step: patch-consumer-secrets
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $producers := index (index .context "apiextensions.crossplane.io/extra-resources") "producers" }}
            {{- if and $producers (eq (len $producers) 1) }}
            {{- $producer := index $producers 0 }}
            {{- $localConsumers := index (index .context "apiextensions.crossplane.io/extra-resources") "consumers" }}
            {{- range $_, $r := $localConsumers }}
            ---
            apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            metadata:
              name: capability-log-write-patch-local-{{ $r.metadata.namespace }}-{{ $r.metadata.name }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: capability-log-write-patch-local-{{ $r.metadata.namespace }}-{{ $r.metadata.name }}
            spec:
              managementPolicies: [Observe, Update]
              watch: true
              providerConfigRef:
                name: kubernetes
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: Secret
                  metadata:
                    name: {{ $r.metadata.name }}
                    namespace: {{ $r.metadata.namespace }}
              references:
              - patchesFrom:
                  apiVersion: v1
                  kind: Secret
                  namespace: opensearch-system
                  name: {{ $producer.metadata.uid }}
                  fieldPath: data.host
              - patchesFrom:
                  apiVersion: v1
                  kind: Secret
                  namespace: opensearch-system
                  name: {{ $producer.metadata.uid }}
                  fieldPath: data.username
              - patchesFrom:
                  apiVersion: v1
                  kind: Secret
                  namespace: opensearch-system
                  name: {{ $producer.metadata.uid }}
                  fieldPath: data.password
            {{- end }}
            {{- if hasKey .observed "resources" }}
            {{- range $_, $cluster := .observed.composite.resource.spec.clusters }}
            {{- with index $.observed.resources (print "remote-consumers-environment-config-" $cluster) }}
            {{- range $_, $r := .resource.status.atProvider.manifest.data.secretRefs }}
            ---
            apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            metadata:
              name: capability-log-write-patch-remote-{{ $cluster }}-{{ $r.namespace }}-{{ $r.name }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: capability-log-write-patch-remote-{{ $cluster }}-{{ $r.namespace }}-{{ $r.name }}
            spec:
              managementPolicies: [Observe, Update]
              watch: true
              providerConfigRef:
                name: kubernetes-{{ $cluster }}
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: Secret
                  metadata:
                    name: {{ $r.name }}
                    namespace: {{ $r.namespace }}
              references:
              - patchesFrom:
                  apiVersion: v1
                  kind: Secret
                  namespace: opensearch-system
                  name: {{ $producer.metadata.uid }}
                  fieldPath: data.host
              - patchesFrom:
                  apiVersion: v1
                  kind: Secret
                  namespace: opensearch-system
                  name: {{ $producer.metadata.uid }}
                  fieldPath: data.username
              - patchesFrom:
                  apiVersion: v1
                  kind: Secret
                  namespace: opensearch-system
                  name: {{ $producer.metadata.uid }}
                  fieldPath: data.password
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
    - step: detect-readiness
      functionRef:
        name: function-auto-ready
